### ISSUE TITLE
GvrShimUnity: getControllerConnectionStatus device index out of range

### ISSUE THREAD

**Issue by zet23t** [googlevr/gvr-unity-sdk#1024]
### SPECIFIC ISSUE ENCOUNTERED

App doesn't start when built with latest Unity version (2019.1.0f2). Logcat repeats the same error continously:

```
04-22 21:25:04.905 28138 28155 E GvrShimUnity: getControllerConnectionStatus device index out of range
04-22 21:25:04.905 28138 28155 E Unity   : GvrShimUnity_getControllerConnectionStatus returned error.
04-22 21:25:04.905 28138 28155 E Unity   :
04-22 21:25:04.905 28138 28155 E Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
```

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2019.1.0f2
- Google VR SDK for Unity: GVR SDK for Unity v1.200.0
- Device manufacturer, model, and O/S:
- Device fingerprint: Lenovo/vega/vega:8.0.0/OVR1.190228.001/5343941:user/release-keys
- Device display metrics:
    mBaseDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1440 x 2560, real 1440 x 2560, largest app 1440 x 2560, smallest app 1440 x 2560, mode 1, defaultMode 1, modes [{id=1, width=1440, height=2560, fps=75.0}], colorMode 0, supportedColorModes [0], hdrCapabilities android.view.Display$HdrCapabilities@1d6308, rotation 0, density 400 (537.882 x 537.388) dpi, layerStack 0, appVsyncOff 1000000, presDeadline 13333333, type BUILT_IN, state OFF, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}
    mBaseDisplayInfo=DisplayInfo{"VR 2D Display", uniqueId "virtual:android:277f1a09-b88d-4d1e-8716-796f114d080b", app 900 x 1125, real 900 x 1125, largest app900 x 1125, smallest app 900 x 1125, mode 5, defaultMode 5, modes [{id=5, width=900, height=1125, fps=60.0}], colorMode 0, supportedColorModes [0], hdrCapabilities null, rotation 0, density 400 (400.0 x 400.0) dpi, layerStack 1, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner android (uid 1000), FLAG_SECURE, removeMode 0}

- Google VR Services:   Packages:
      versionName=1.20.234682102.release_aio
- Viewer manufacturer & model: Lenovo Mirage Solo
- Link to Unity project that reproduces the issue: n/a

### STEPS TO REPRODUCE THE ISSUE
 1. Build an app with given SDK & Unity version
 1. Try to start the app

**Comment by rusmaxham** [comment]
This is a known issue with Unity 2019.1.  Unity is working on a fix.

**Comment by rusmaxham** [comment]
This should be fixed with com.unity.xr.googlevr.android package version 1.18.4 from Unity.

**Comment by adammpkins** [comment]
@rusmaxham Am I missing something? Is 1.18.4 in the package manager equivalent to the 1.2 release the original poster mentioned? Running into this same bug with 2019.1.12f1 and sdk release v1.200.1

Need functionality from the <1.2 release as 64 bit support is required this week.

**Comment by rusmaxham** [comment]
There was an issue with how Unity builds with the Cardboard/Daydream SDK and the GoogleVR SDK for Unity that was resolved in com.unity.xr.googlevr.android@1.18.4.  It is separate from the GoogleVR SDK for Unity v1.200 which contains 64 bit support.  com.unity.xr.googlevr.android is a package released by Unity.  GoogleVR SDK for Unity is a unitypackage released by Google.  Both are needed for 64 bit build support.

**Comment by renanmgs** [comment]
Still getting this error even with com.unity.xr.googlevr.android@1.18.4
![image](https://user-images.githubusercontent.com/30127127/63217290-40ae8380-c11a-11e9-8470-3ea9854bcf0e.png)

**Comment by diegodias** [comment]
> Still getting this error even with com.unity.xr.googlevr.android@1.18.4
> ![image](https://user-images.githubusercontent.com/30127127/63217290-40ae8380-c11a-11e9-8470-3ea9854bcf0e.png)

Getting exactly the same error
