### ISSUE TITLE
Errors reguarding "global game manager"

### ISSUE THREAD

**Issue by neinte** [googlevr/gvr-unity-sdk#584]
Unity gives me the message when I download gvr 1.5. I'm running Unity 5.6.1 Personal Edition 

Assets/GoogleVR/Scripts/Controller/Internal/Emulator/PhoneEvent.cs(19,12): error CS0400: The type or namespace name `Google' could not be found in the global namespace. Are you missing an assembly reference?

**Comment by vinhui** [comment]
Right click on the Google.ProtocolBuffers dll in the plugins folder and click reimport. That should fix it, a restart of unity might also help.

**Comment by chaosemer** [comment]
Yes, that's the right solution. Please reopen if you still are having issues.

**Comment by Karel-Chabera** [comment]
I've tried all the above suggestions but i'm still having the same issue. I'm using Unity 2017.2.0p1

**Comment by rusmaxham** [comment]
What version of the GVR SDK for Unity are you using?
