### ISSUE TITLE
Controller not working when Time.timeScale = 0

### ISSUE THREAD

**Issue by wojwen** [googlevr/gvr-unity-sdk#690]
Few days ago I posted a thread about this bug. It's about the controller not working properly when Time.timeScale is set to 0. The controller isn't visible if Time.timeScale i 0 from the start, it doesn't interact with UI and tooltips are invisible. I managed to fix this by making following changes:
In `GvrLaserVisual.cs` replace
`return lerpSpeed > 0.0f ? lerpSpeed * Time.deltaTime : 1.0f;`
with
`return lerpSpeed > 0.0f ? lerpSpeed * Time.unscaledDeltaTime : 1.0f;`
In `GvrControllerVisual.cs` replace
`float deltaTime = Time.deltaTime;`
with
`float deltaTime = Time.unscaledDeltaTime;`
and in `GvrArmModel.cs` replace
`float animationDelta = DELTA_ALPHA * Time.deltaTime;`
with
`float animationDelta = DELTA_ALPHA * Time.unscaledDeltaTime;`

**Comment by rusmaxham** [comment]
Great suggestion.  We're integrating something like this now.

**Comment by dsternfeld7** [comment]
Addressed in v1.100.0

**Comment by terreb** [comment]
Has this been fixed? I still have a similar problem with Google Cardboard game using Unity 2018.2 and Google VR for Unity 1.150.0. When Time.timeScale is set to 0 the reticle pointer disappears.

**Comment by rusmaxham** [comment]
Could you try replacing instances of `Time.deltaTime` in **GvrReticlePointer.cs** with `Time.unscaledDeltaTime` and see if that addresses your issue?

**Comment by terreb** [comment]
@rusmaxham, thank you a lot, the solution works perfectly!

**Comment by rusmaxham** [comment]
Good to know.  We'll get this fixed in the next release.

**Comment by rusmaxham** [comment]
This is now fixed in [v1.170](https://github.com/googlevr/gvr-unity-sdk/releases).
