### ISSUE TITLE
Instant preview no output (installed version doesn't much local version)

### ISSUE THREAD

**Issue by Yunqi-Hu** [googlevr/gvr-unity-sdk#773]
<Brief summary of the issue you encountered>
I am trying to set up the daydream instant preview on Mac. I connected the phone through adb, it's all good and I am able to build app to the phone. On the phone, the instant preview app shows it's connected to the editor. However, when I play the project, there is no output on the phone. Here is the console info

It's always the same warning "installed version doesn't much local version". I tried different versions of Gvr Unity SDK, but the local version is always 1.0.0.64 and the installed version changes corresponding to the SDK versions. Also, the instant preview app on the phone is installed through the instantPreview script on the run, which means it always comes from SDK I am currently using. I have been working on this bug for over a week and didn't have any progress yet.
<img width="730" alt="screen shot 2017-11-07 at 8 28 35 am" src="https://user-images.githubusercontent.com/10550363/32505294-b04ce1f6-c396-11e7-9ea2-b9363a95f86c.png">

Found using:
 * Google VR SDK version: 1.100.1
 * Unity version: 2017.1.2f1
 * Phone manufacturer, model, and O/S version: ASUS ZenFone AR
 * Viewer manufacturer & model: Daydream View

**Comment by gstanlo** [comment]
Hey Yunqi-Hu, there is currently a bug in the osx version that should be fixed soon. We recommend disabling the "install on play" check box after you've successfully installed the app once.

As for the phone output, have you been able to use it successfully with the GVR Demo scene or using the controller-only mode? Does it ever list itself as connected?

**Comment by rusmaxham** [comment]
The Instant Preview version mismatch issue has been resolved in the latest [release](https://github.com/googlevr/gvr-unity-sdk/releases).

**Comment by ylluminarious** [comment]
@Yunqi-Hu @gstanlo 

I had a similar (same?) issue in Unity 2017.2.0p1.

I had very similar warnings in my editor console and whenever I ran my game with Instant Preview, it would crash. There were no errors in my editor console, though. I'm not sure if crashing is what you mean by there being "no output on the phone" @Yunqi-Hu.

Fortunately, after disabling `Install Apk On Run`, everything worked fine. This only happened after upgrading to 2017.2 and did not happen in an older version of Unity 2017.1. I have to guess that newer versions of Unity are doing something weird which is causing these issues.

**Comment by Yunqi-Hu** [comment]
@gstanlo Hi, thanks for your reply. Yes, I have tried to disable "install on the run" after there is an app installed on my phone. However, it still doesn't work. Also, I can not get instant preview to work in GVR Demo scene in either mode. I have checked my terminal, my phone is connected. And on my phone, it always shows this, which I believe meaning my phone is connected. 
<img width="298" alt="screen shot 2017-11-08 at 1 55 33 pm" src="https://user-images.githubusercontent.com/10550363/32576897-2226deb6-c48d-11e7-97b0-7f9e472c8c45.png">

**Comment by ylluminarious** [comment]
@Yunqi-Hu Have you tried launching Instant Preview through the Daydream menu? That's the only way I could get it to work. The vanilla Android interface that you show there did not work for me either.

**Comment by Yunqi-Hu** [comment]
@ylluminarious  Hi, thanks for sharing your experience. I have tried what you suggested to open instant preview from daydream menu, unfortunately, it still doesn't work. And actually, I was able to get it work from the vanilla Android interface like a month ago. But just couldn't get it to work now...

**Comment by Yunqi-Hu** [comment]
@rusmaxham Hi, thank you for the notice about the new sdk release. I have tried the new SDK, somehow, it still doesn't work for me. This is the waring from the console. May I know what does installed version and local version means respectively here?
<img width="760" alt="screen shot 2017-11-08 at 1 50 12 pm" src="https://user-images.githubusercontent.com/10550363/32577488-f378b97a-c48e-11e7-968c-f42c61d0fa64.png">

**Comment by rusmaxham** [comment]
Do you get that warning on every Play in editor?  It is expected to warn the first time.

**Comment by ylluminarious** [comment]
@Yunqi-Hu Hmm, ok. The last piece of advice that I have is that you may not have your scene's camera tagged with the `MainCamera` tag. If your camera doesn't have this tag, Instant Preview won't work and troubleshooting it can be a pain. I had a struggle with it over [at this ticket.](https://github.com/googlevr/gvr-instant-preview/issues/10)

**Comment by Yunqi-Hu** [comment]
@ylluminarious I checked the MainCamera tag. That doesn't seem to be my problem. Anyway, thank you!

**Comment by ylluminarious** [comment]
@Yunqi-Hu Well, sorry about that. Best of luck to you!

**Comment by Yunqi-Hu** [comment]
@rusmaxham That warning appears whenever I enable the "install on the run"

**Comment by Yunqi-Hu** [comment]
I got it work on another Mac of mine, using the latest SDK and unity 2017.2.0f3 without any change of settings...

**Comment by rusmaxham** [comment]
That's odd.  Glad it is working for you now.

As an aside, we recommend upgrading to [Unity 2017.2.0p1](https://unity3d.com/unity/qa/patch-releases/2017.2.0p1) for Daydream development, as it has a fix for the Daydream controller freeze after app background/foreground.

**Comment by Yunqi-Hu** [comment]
@rusmaxham Thanks for letting me know. You guys are so helpful!
