### ISSUE TITLE
how to disable the dialog about installing google vr service 

### ISSUE THREAD

**Issue by nanweiqing** [googlevr/gvr-unity-sdk#832]
<Brief summary of the issue you encountered>
I am building a vr for unity video app and keep on getting warning to install Google VR services,  this breaks the user experience, is there any api which I can call and suppress the warning message?
Found using:
 * Google VR SDK version: 1.120
 * Unity version:  2017.2.0f3
 * Phone manufacturer, model, and O/S version: xiaomi  Android7.0
 * Viewer manufacturer & model: Android7.0

Steps to reproduce the issue:
 1. Build the GVR demo scene.
 2. Click on Virtual Reality supported and choose cardboard.
 3.Run it on the phone,it shows the dialog when opens the app

Workarounds:
___

Additional comments:
___

**Comment by fredsa** [comment]
As mentioned in [gvr-android-sdk #405](https://github.com/googlevr/gvr-android-sdk/issues/405#issuecomment-358134843), we're planning to remove the "Google VR Services" installation prompt on devices that aren't Daydream-ready. 

Please follow that issue for future updates.

**Comment by nanweiqing** [comment]
thank you very much，by the way，will it provides some methods to cancel the close button and setting button on the view ?

**Comment by tedtheodore** [comment]
Was this introduced at all?

**Comment by rusmaxham** [comment]
This should be fixed in [v1.130.1](https://github.com/googlevr/gvr-unity-sdk/releases).

**Comment by i3games** [comment]
It is not fixed and still triggers the prompt on non-daydream devices like the Moto G5 on Chrome 71
